@host = 192.168.0.183
@port = 8210
@keyPath = /test/rules
@baseUrl = http://{{host}}:{{port}}{{keyPath}}
@baseUrlNginx = http://{{host}}/kvstore{{keyPath}}

### CORS preflight via nginx /kvstore route
OPTIONS {{baseUrlNginx}}
Origin: http://{{host}}
Access-Control-Request-Method: POST
Access-Control-Request-Headers: Content-Type, Authorization, X-Requested-With

### CORS preflight for nginx FileStore GET
OPTIONS {{baseUrlNginx}}
Origin: http://{{host}}
Access-Control-Request-Method: GET

### Write JSON value to FileStore
POST {{baseUrl}}
content-type: application/json

{
  "name": "test-rule",
  "enabled": true,
  "updatedBy": "http-test"
}

### Read value from FileStore
GET {{baseUrl}}

### Write JSON value via nginx kvstore route (Angular app path style)
POST {{baseUrlNginx}}
content-type: application/json

{
  "name": "test-rule",
  "enabled": true,
  "updatedBy": "http-test-nginx"
}

### Read value via nginx kvstore route (Angular app path style)
GET {{baseUrlNginx}}
