@host = 192.168.0.183
@port = 8092
@baseUrl = http://{{host}}:{{port}}
@baseUrlNginx = http://{{host}}

### Publish to broker HTTP facade on yaha2
POST {{baseUrl}}/publish
content-type: application/json

{
  "topic": "first/study/main/light/light on time/set",
  "value": "off",
  "timestamp": "2026-05-06T06:26:50.887Z"
}

### Publish via nginx route used by Angular app
PUT {{baseUrlNginx}}/publish
content-type: application/json

{
  "topic": "first/study/main/light/light on time/set",
  "value": "off",
  "reason": [{ "message": "request by browser", "timestamp": "2026-05-06T06:26:50.887Z" }]
}
