[mqtt]
host = 127.0.0.1
port = 1883
clientId = yaharemoteserviceclient
reconnectDelayMs = 1000
keepAliveIntervalMs = 30000
loopSleepMs = 20

[filestore]
host = 127.0.0.1
port = 8210
filename = /remoteservice/services
# RemoteService subscribes to <topicPrefix>/# and reloads mapping on matching keyPath monitor events.
topicPrefix = $MONITOR/FileStore

[remoteservice]
listenHost = 0.0.0.0
listenPort = 9123
subscribeQoS = 1
