#pragma once

/**
 * @file rules_tree_processor.h
 * @brief End-to-end processing for complete automation rule trees.
 */

#include <cstddef>
#include <set>
#include <string>
#include <vector>

#include "yaha/automation/expression_evaluator.h"
#include "yaha/automation/rules_tree_parser.h"
#include "yaha/message/message.h"

namespace yaha {

/**
 * @brief Result of processing a complete rule tree.
 */
struct RulesTreeProcessingResult {
    bool success{false};                       ///< True when all processed rules finished without errors.
    std::size_t processedRules{0U};            ///< Number of detected rule objects processed.
    std::size_t triggeredRules{0U};            ///< Number of rules that emitted one message.
    std::vector<Message> messages;             ///< Outbound messages generated by triggered rules.
    std::set<std::string> usedVariables;       ///< Union of all variables used by processed rules.
    std::vector<std::string> errors;           ///< Processing errors with source path context.
};

/**
 * @brief Processes all rule objects found in a structured rules tree.
 */
class RulesTreeProcessor {
public:
    /**
     * @brief Traverses and processes every rule object in a rule tree.
     *
     * A node is treated as a rule object when it is an object containing
     * a `topic` field. Each matching object is processed through
     * `SingleRuleProcessor`.
     *
     * @param root Structured rule tree root.
     * @param variables Runtime external variable map.
     * @return Aggregate processing result over all discovered rules.
     */
    [[nodiscard]] static RulesTreeProcessingResult process(
        const RuleTreeNode& root,
        const ExpressionEvaluator::VariableMap& variables);
};

} // namespace yaha
